Support arbitrary notification daemons
QubesOS/qubes-meta-packages pull request #69
Opened 2023-11-26 03:46 UTC by DemiMarie

Qubes OS only recomments that _a_ notification daemon be present, not that specifically xfce4-notifyd is present.  Having multiple notification daemons installed leads to problems.  Instead, require the desktop-notification-daemon capability, which is provided by multiple notification daemons.  This allows using an alternate notification daemon, such as a Qubes-specific one currently in development.

Fixes: QubesOS/qubes-issues#8729

2024-09-28 02:39 UTC, marmarek commented on rpm_spec/qubes-vm-meta-packages.spec.in
> +Recommends: xfce4-notifyd
This unfortunately doesn't work as desired. You can install alternative notification daemon and then remove `xfce4-notifyd`. But if you do that the other way around (install another notification daemon and only then install `qubes-vm-recommended`) then the `xfce4-notifyd` gets installed anyway. It means, it's incompatible with requesting another notification daemon at template build time.

Maybe a Debian-like approach would work? Specifically, require `(xfce4-notifyd or desktop-notification-daemon)` and hope the first one will be preferred if not installed already (this behavior is defined in Debian, but I don't know what DNF will do).

Or, maybe ignore the issue, in preparation for switching default to the `qubes-notification-agent`?

BTW, it's quite confusing that the right package to satisfy `desktop-notification-daemon` is `qubes-notification-agent` and not `qubes-notification-daemon` which also exists...

2024-09-30 02:46 UTC, marmarek requested changes

2024-09-30 02:46 UTC, marmarek commented on rpm_spec/qubes-vm-meta-packages.spec.in
> +Recommends: (xfce4-notifyd or desktop-notification-daemon)
> and hope the first one will be preferred if not installed already

So, this doesn't work. Installing this package when no notification daemon is installed yet pulls in `dunst` (at least in my test, it could be also non-deterministic...). So, if you have no better ideas, it's probably best to go back to the initial version (and at a later time switch to the qubes-notification-agent).

2024-09-30 03:02 UTC, DemiMarie commented on rpm_spec/qubes-vm-meta-packages.spec.in
> +Recommends: (xfce4-notifyd or desktop-notification-daemon)
Does that mean that this PR should be closed?

2024-09-30 03:50 UTC, marmarek commented on rpm_spec/qubes-vm-meta-packages.spec.in
> +Recommends: (xfce4-notifyd or desktop-notification-daemon)
No, revert to its initial shape (`Recommends: xfce4-notifyd`)

2025-03-25 18:23 UTC, marmarek approved these changes

2025-03-25 18:23 UTC, merged